### ISSUE TITLE
update RStudio Files panel after fetch...()

### ISSUE THREAD

**Issue by katrinleinweber** [jonmcalder/exercism#3]
Currently (exercism pkg v0.1.1 & RStudio v1.1.359) one has to click the "Refresh File Listing" button after a `fetch…()` to see the newly downloaded folder. Since [RStudio lists the underlying function](https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml#L1925) could it be triggered automatically by the package?

**Comment by jonmcalder** [comment]
Thanks for opening this Katrin! Definitely seems feasible as long as it's exposed via the `rstudioapi`. I'll look into it.

FYI, as it happens I was working on this package yesterday, and am most of the way to getting the submit functionality in. Took a while cos I had lots of issues setting up the exercism.io environment locally but I'm well on the way now :-)

**Comment by jonmcalder** [comment]
I checked a few times with RStudio 1.0.143 and 1.1.372 and in both cases the file lists were refreshed automatically. Also tried checking both on Windows and on an Ubuntu VM and both refreshed immediately reflecting the new folders. 

It seems unlikely that the issue would be related specifically to RStudio v1.1.359 (and neighbouring builds), but I suppose it's possible. Could also be different behavior for Mac?

Can you re-test and see if you are able to reproduce this issue consistently?

**Comment by katrinleinweber** [comment]
Yes, it is (on macOS 10.12.6), ever since I installed the package when you first published it. In late autumn, I can test on Windows and Linux VMs as well :-)

I used `devtools::install_github("jonmcalder/exercism")` again just now: same behavior. In case you have a more recent development version offline, can you please upload it?

Also, there seems to be a 2-step refresh process in RStudio: After a `fetch()`, the new folder does appear, but appended. It gets sorted (by `Name`, `Size` or `Modified on`) into the correct position only upon clicking `Refresh`.

**Comment by jonmcalder** [comment]
> Also, there seems to be a 2-step refresh process in RStudio: After a fetch(), the new folder does appear, but appended. It gets sorted (by Name, Size or Modified on) into the correct position only upon clicking Refresh.

I don't quite understand what you mean here - I thought you said initially that the new folder does not appear (at all) until you do a Refresh? Whereas now you are saying that it appears but is just appended rather than being placed in the right order based on the sorting.

Are you saying that there is different behaviour for `fetch_problem()` and `fetch_next()`? Or does the same thing apply for both? There isn't a `fetch()` function.

**Comment by katrinleinweber** [comment]
I meant both `fetch…()` functions, sorry. I have to conclude that I overlooked the folder indeed appearing, just out-of-(alphabetical-)order at the very bottom, below the *scroll fold*, so to speak. The click on "Refresh..." is only needed to get the sorting right.

**Comment by jonmcalder** [comment]
Ok cool no worries. Ah yes I hadn't really factored in the "below the scroll fold" scenario, since I was mostly testing in a dummy `~/exercism` folder in my dev environment which wasn't populated with lots of exercise folders. It makes sense now that it appearing out of order at the bottom effectively means it is "temporarily" invisible.

I did have a look but can't see any obvious way to call the refresh since though it is documented it doesn't seem be an exposed call (unless I'm just missing something). Anyway now that you've clarified, things, even if there was a refresh, it wouldn't always be visible without scrolling within the directory anyway. Maybe it would be better to open one (or more) of the files from the exercise in RStudio once they have been fetched? Do you think this is a safe default option? If so then I'll add this and maybe just include a parameter to disable it.

**Comment by katrinleinweber** [comment]
I think auto-open is a good default, maybe even an idea for [#5](https://github.com/jonmcalder/exercism/issues/5#issuecomment-332268975). Even all three: ReadMe, tests and the exercise itself.
